{{- if not .Values.auth.existingPasswordSecret }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "postgres-backup-local.fullname" . }}
  labels:
  {{- include "postgres-backup-local.labels" . | nindent 4 }}
type: Opaque
stringData:
  POSTGRES_USER: {{ .Values.auth.postgres_user }}
  POSTGRES_PASSWORD: {{ .Values.auth.postgres_password }}
  {{ end }}